# Generated by Django 5.0.7 on 2024-08-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('motor_id', models.IntegerField()),
                ('entry_text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.IntegerField()),
                ('setting1', models.FloatField()),
                ('setting2', models.FloatField()),
                ('setting3', models.FloatField()),
                ('s1', models.FloatField()),
                ('s2', models.FloatField()),
                ('s3', models.FloatField()),
                ('s4', models.FloatField()),
                ('s5', models.FloatField()),
                ('s6', models.FloatField()),
                ('s7', models.FloatField()),
                ('s8', models.FloatField()),
                ('s9', models.FloatField()),
                ('s10', models.FloatField()),
                ('s11', models.FloatField()),
                ('s12', models.FloatField()),
                ('s13', models.FloatField()),
                ('s14', models.FloatField()),
                ('s15', models.FloatField()),
                ('s16', models.FloatField()),
                ('s17', models.IntegerField()),
                ('s18', models.IntegerField()),
                ('s19', models.FloatField()),
                ('s20', models.FloatField()),
                ('s21', models.FloatField()),
            ],
            options={
                'db_table': 'motor',
            },
        ),
    ]
